fileVersion: 1
id: "11"
mappingDefinitions:
  PROD:
    database: BECHEIRAZ
    schema: WORKPROD
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TEST:
    database: BECHEIRAZ
    schema: WORKTEST
  WORK:
    database: BECHEIRAZ
    schema: WORKDEV
name: New Environment
type: Environment
